# JPMS module name -> Maven coordinates mapping for org.gradlex.java-module-dependencies
javafx.base=org.openjfx:javafx-base
javafx.graphics=org.openjfx:javafx-graphics
javafx.controls=org.openjfx:javafx-controls
javafx.fxml=org.openjfx:javafx-fxml
com.dlsc.fxmlkit=com.dlsc.fxmlkit:fxmlkit
com.dlsc.gemsfx=com.dlsc.gemsfx:gemsfx
atlantafx.base=io.github.mkpaz:atlantafx-base
io.avaje.inject=io.avaje:avaje-inject
jakarta.inject=jakarta.inject:jakarta.inject-api
com.fasterxml.jackson.core=com.fasterxml.jackson.core:jackson-core
com.fasterxml.jackson.annotation=com.fasterxml.jackson.core:jackson-annotations
com.fasterxml.jackson.databind=com.fasterxml.jackson.core:jackson-databind
com.fasterxml.jackson.datatype.jsr310=com.fasterxml.jackson.datatype:jackson-datatype-jsr310
ai.timefold.solver.core=ai.timefold.solver:timefold-solver-core
com.github.librepdf.openpdf=com.github.librepdf:openpdf
org.kordamp.ikonli.core=org.kordamp.ikonli:ikonli-core
org.kordamp.ikonli.javafx=org.kordamp.ikonli:ikonli-javafx
org.kordamp.ikonli.materialdesign2=org.kordamp.ikonli:ikonli-materialdesign2-pack
